### ISSUE TITLE
pi able to write to I2C servo bus

### ISSUE THREAD

**Issue by zeke2856** [Rolling-Blocks/RB-CODE-Prototype-1#3]
have had issues getting pi to send servo commands consistently

**Comment by zeke2856** [comment]
ubuntu@ubuntu:~/mech_display$ python3 write_display.py 
0
Traceback (most recent call last):
  File "write_display.py", line 49, in <module>
    servos.write_servos()
  File "write_display.py", line 37, in write_servos
    self.bus.i2c_rdwr(write)
  File "/usr/local/lib/python3.8/dist-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
TimeoutError: [Errno 110] Connection timed out

**Comment by zeke2856** [comment]
the issue was with hardware. The Clock Wire was set to the ground which bogged down the bus and made the error seem like it was software-related. Also, a bodge wire was missing from one of the stm32 daughter boards
